"""§63 #7j Phase 1-b -- MEASUREMENT ONLY.  Does the receive path tolerate a
spec-correct, continuously-valid scrambled Logical Idle stream?

J-1 predicts it does.  Every row here is a probe: it emits raw timestamped
events and asserts nothing (§22.92).  Pairing and verdicts happen offline in
`analyse_rx.py`, which opens with the known-answer test against Base 2.1
p.700's two published tables before it reads a DUT byte.

The stimulus is generated by `rx_golden.Descrambler` -- the same operation in
both directions (Base 2.1 App. C.1 p.698: "THE DESCRAMBLE ROUTINE IS IDENTICAL
TO THE SCRAMBLE ROUTINE"), so scrambling here is the model, not the DUT.

Event grammar, one per line:

    RX|<row>|<cycle>|<time_ns>|<what>|<fields...>

      RX|..|SYM|<driven_byte>|<driven_k>       what went in that cycle
      RX|..|OUT|<idle>|<ts1>|<ts2>|<pol>       the per-lane validity outputs
      RX|..|AXI|<tdata>|<tkeep>|<tlast>        an AXIS beat out of the closure
"""
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles

from rx_golden import (COM, SDP, STP, END, TS1_ID, GEN1,
                       Descrambler, ts_ordered_set)

PIPE_WIDTH = 8


async def setup(dut):
    cocotb.start_soon(Clock(dut.clk_i, 10, units="ns").start())
    cocotb.start_soon(Clock(dut.pipe_rx_usr_clk_i, 10, units="ns").start())
    dut.rst_i.value = 1
    dut.en_i.value = 0
    dut.link_up_i.value = 0
    dut.pipe_data_i.value = 0
    dut.pipe_data_valid_i.value = 0
    dut.pipe_data_k_i.value = 0
    dut.pipe_sync_header_i.value = 0
    dut.pipe_block_start_i.value = 0
    dut.pipe_width_i.value = PIPE_WIDTH
    dut.num_active_lanes_i.value = 1
    dut.curr_data_rate_i.value = GEN1
    dut.m_dllp_axis_tready.value = 1
    await ClockCycles(dut.pipe_rx_usr_clk_i, 10)
    dut.rst_i.value = 0
    dut.en_i.value = 1
    dut.link_up_i.value = 1
    await ClockCycles(dut.pipe_rx_usr_clk_i, 6)


def _b0(sig):
    try:
        return int(sig.value) & 1
    except Exception:
        return -1


async def drive_and_record(dut, row, syms, tail=80):
    """Drive one Symbol per clock on Lane 0, valid HIGH for every driven Symbol.

    Sampling runs CONTINUOUSLY from before the first Symbol (§22.89) in two
    independent coroutines, so no observation depends on the stimulus loop's
    phase.  Nothing is filtered here.
    """
    stop = {"go": True}

    async def out_monitor():
        c = 0
        while stop["go"]:
            await RisingEdge(dut.pipe_rx_usr_clk_i)
            dut._log.info("RX|%s|%d|%.1f|OUT|%d|%d|%d|%d"
                          % (row, c, cocotb.utils.get_sim_time(units="ns"),
                             _b0(dut.idle_valid_o), _b0(dut.ts1_valid_o),
                             _b0(dut.ts2_valid_o), _b0(dut.polarity_inverted_o)))
            c += 1

    async def axis_monitor():
        c = 0
        while stop["go"]:
            await RisingEdge(dut.clk_i)
            if int(dut.m_dllp_axis_tvalid.value) & 1:
                dut._log.info("RX|%s|%d|%.1f|AXI|%08x|%x|%d"
                              % (row, c, cocotb.utils.get_sim_time(units="ns"),
                                 int(dut.m_dllp_axis_tdata.value) & 0xFFFFFFFF,
                                 int(dut.m_dllp_axis_tkeep.value) & 0xF,
                                 int(dut.m_dllp_axis_tlast.value) & 1))
            c += 1

    cocotb.start_soon(out_monitor())
    cocotb.start_soon(axis_monitor())

    for i, (b, k) in enumerate(syms):
        dut.pipe_data_i.value = b & 0xFF
        dut.pipe_data_k_i.value = k & 0x1
        dut.pipe_data_valid_i.value = 1
        dut._log.info("RX|%s|%d|%.1f|SYM|%02x|%d"
                      % (row, i, cocotb.utils.get_sim_time(units="ns"), b, k))
        await RisingEdge(dut.pipe_rx_usr_clk_i)

    # Tail: valid stays HIGH and the idle stream CONTINUES, because that is the
    # whole question -- a tail with valid low would measure today's behaviour,
    # not the behaviour under test.
    tx = drive_and_record.tx
    for _ in range(tail):
        b = tx.symbol(0x00, is_k=False)
        dut.pipe_data_i.value = b
        dut.pipe_data_k_i.value = 0
        dut.pipe_data_valid_i.value = 1
        await RisingEdge(dut.pipe_rx_usr_clk_i)
    stop["go"] = False
    await ClockCycles(dut.pipe_rx_usr_clk_i, 2)


def idle_run(tx, n):
    """n Symbols of scrambled Logical Idle: data 00h, K=0 (sec 4.2.2 p.195)."""
    return [(tx.symbol(0x00, is_k=False), 0) for _ in range(n)]


def ts1_prefix(tx, link=0x05, lane=0x00):
    ts = ts_ordered_set(TS1_ID, link=link, lane=lane)
    out = [(tx.symbol(ts[0][0], ts[0][1]), ts[0][1])]
    out += [(tx.symbol(b, k, True), k) for b, k in ts[1:]]
    return out


def dllp_frame(tx, payload):
    out = [(tx.symbol(SDP, is_k=True), 1)]
    out += [(tx.symbol(p, is_k=False), 0) for p in payload]
    out += [(tx.symbol(END, is_k=True), 1)]
    return out


# ------------------------------------------------------------------ R1
@cocotb.test()
async def r1_continuous_idle_only(dut):
    """320 Symbols of nothing but spec-golden scrambled Logical Idle, valid high
    throughout, after a COM re-seed.  J-1's core case."""
    await setup(dut)
    tx = Descrambler()
    drive_and_record.tx = tx
    syms = [(tx.symbol(COM, is_k=True), 1)] + idle_run(tx, 320)
    await drive_and_record(dut, "R1", syms)


# ------------------------------------------------------------------ R2
@cocotb.test()
async def r2_idle_packet_idle(dut):
    """idle -> TS1 -> idle -> framed DLLP -> idle, valid HIGH the whole way.

    The shape #7j-2 would put on the wire.  Asks whether the packet still
    decodes when it is embedded in a continuous idle stream instead of arriving
    after a valid gap."""
    await setup(dut)
    tx = Descrambler()
    drive_and_record.tx = tx
    syms = [(tx.symbol(COM, is_k=True), 1)]
    syms += idle_run(tx, 64)
    syms += ts1_prefix(tx)
    syms += idle_run(tx, 32)
    syms += dllp_frame(tx, [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34])
    syms += idle_run(tx, 64)
    await drive_and_record(dut, "R2", syms)


# ------------------------------------------------------------------ R3
@cocotb.test()
async def r3_control_gapped_idle(dut):
    """The CONTROL (§22.81): the SAME packet, but reached the way the link
    reaches it TODAY -- a TS1, then a valid GAP, then the DLLP.  Whatever R2
    shows is only meaningful against this."""
    await setup(dut)
    tx = Descrambler()
    drive_and_record.tx = tx
    syms = [(tx.symbol(COM, is_k=True), 1)]
    syms += ts1_prefix(tx)
    pkt = dllp_frame(tx, [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34])

    stop = {"go": True}
    cocotb.start_soon(_out_mon(dut, "R3", stop))
    cocotb.start_soon(_axi_mon(dut, "R3", stop))
    for b, k in syms:
        dut.pipe_data_i.value = b
        dut.pipe_data_k_i.value = k
        dut.pipe_data_valid_i.value = 1
        await RisingEdge(dut.pipe_rx_usr_clk_i)
    # the gap: valid LOW, data held at 0 -- today's behaviour
    dut.pipe_data_valid_i.value = 0
    await ClockCycles(dut.pipe_rx_usr_clk_i, 32)
    for b, k in pkt:
        dut.pipe_data_i.value = b
        dut.pipe_data_k_i.value = k
        dut.pipe_data_valid_i.value = 1
        await RisingEdge(dut.pipe_rx_usr_clk_i)
    dut.pipe_data_valid_i.value = 0
    await ClockCycles(dut.pipe_rx_usr_clk_i, 80)
    stop["go"] = False
    await ClockCycles(dut.pipe_rx_usr_clk_i, 2)


async def _out_mon(dut, row, stop):
    c = 0
    while stop["go"]:
        await RisingEdge(dut.pipe_rx_usr_clk_i)
        dut._log.info("RX|%s|%d|%.1f|OUT|%d|%d|%d|%d"
                      % (row, c, cocotb.utils.get_sim_time(units="ns"),
                         _b0(dut.idle_valid_o), _b0(dut.ts1_valid_o),
                         _b0(dut.ts2_valid_o), _b0(dut.polarity_inverted_o)))
        c += 1


async def _axi_mon(dut, row, stop):
    c = 0
    while stop["go"]:
        await RisingEdge(dut.clk_i)
        if int(dut.m_dllp_axis_tvalid.value) & 1:
            dut._log.info("RX|%s|%d|%.1f|AXI|%08x|%x|%d"
                          % (row, c, cocotb.utils.get_sim_time(units="ns"),
                             int(dut.m_dllp_axis_tdata.value) & 0xFFFFFFFF,
                             int(dut.m_dllp_axis_tkeep.value) & 0xF,
                             int(dut.m_dllp_axis_tlast.value) & 1))
        c += 1


# ------------------------------------------------------------------ R4 / R5
# R2 vs R3 differ in TWO ways at once -- whether the mid-stream gap is filled,
# and whether the stream continues after the packet.  That is a confound, and a
# two-variable comparison cannot attribute the result to either one (§22.80's
# sibling: a control must isolate the variable under test).  R4 and R5 complete
# the 2x2 so each variable is varied alone.
#
#            mid-stream gap        after the packet        row
#            --------------        ----------------        ---
#            idle, valid high      idle, valid high        R2
#            valid LOW             valid LOW               R3
#            valid LOW             idle, valid high        R4
#            idle, valid high      valid LOW               R5

async def _drive(dut, syms):
    for b, k in syms:
        dut.pipe_data_i.value = b & 0xFF
        dut.pipe_data_k_i.value = k & 0x1
        dut.pipe_data_valid_i.value = 1
        await RisingEdge(dut.pipe_rx_usr_clk_i)


async def _gap(dut, n):
    dut.pipe_data_valid_i.value = 0
    await ClockCycles(dut.pipe_rx_usr_clk_i, n)


@cocotb.test()
async def r4_lowgap_then_idle_tail(dut):
    """valid-LOW mid-stream gap, but the stream CONTINUES after the packet."""
    await setup(dut)
    tx = Descrambler()
    stop = {"go": True}
    cocotb.start_soon(_out_mon(dut, "R4", stop))
    cocotb.start_soon(_axi_mon(dut, "R4", stop))
    await _drive(dut, [(tx.symbol(COM, is_k=True), 1)] + ts1_prefix(tx))
    await _gap(dut, 32)
    await _drive(dut, dllp_frame(tx, [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34]))
    await _drive(dut, idle_run(tx, 80))
    stop["go"] = False
    await ClockCycles(dut.pipe_rx_usr_clk_i, 2)


@cocotb.test()
async def r5_idle_gap_then_low_tail(dut):
    """idle-filled mid-stream gap, but the stream STOPS after the packet."""
    await setup(dut)
    tx = Descrambler()
    stop = {"go": True}
    cocotb.start_soon(_out_mon(dut, "R5", stop))
    cocotb.start_soon(_axi_mon(dut, "R5", stop))
    await _drive(dut, [(tx.symbol(COM, is_k=True), 1)] + ts1_prefix(tx))
    await _drive(dut, idle_run(tx, 32))
    await _drive(dut, dllp_frame(tx, [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34]))
    await _gap(dut, 80)
    stop["go"] = False
    await ClockCycles(dut.pipe_rx_usr_clk_i, 2)


# ------------------------------------------------------------------ R6
# How much trailing stream is enough?  The 2x2 says the tail decides; this says
# by how much.  Swept at two different mid-stream gap lengths so the answer is
# not read off a single route (§22.85).

@cocotb.test()
async def r6_tail_length_sweep(dut):
    """For each (gap, tail) pair, drive TS1 -> gap -> DLLP -> tail and report
    whether any AXIS beat appeared.  One raw line per pair; the threshold is
    computed offline, not here."""
    for gap in (0, 32):
        for tail in (0, 2, 4, 6, 8, 10, 12, 14, 16, 20, 24):
            await setup(dut)
            tx = Descrambler()
            beats = []

            async def mon():
                while True:
                    await RisingEdge(dut.clk_i)
                    if int(dut.m_dllp_axis_tvalid.value) & 1:
                        beats.append((int(dut.m_dllp_axis_tdata.value) & 0xFFFFFFFF,
                                      int(dut.m_dllp_axis_tkeep.value) & 0xF,
                                      int(dut.m_dllp_axis_tlast.value) & 1))

            h = cocotb.start_soon(mon())
            await _drive(dut, [(tx.symbol(COM, is_k=True), 1)] + ts1_prefix(tx))
            if gap:
                await _gap(dut, gap)
            await _drive(dut, dllp_frame(tx, [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34]))
            if tail:
                await _drive(dut, idle_run(tx, tail))
            # Settle with valid LOW so nothing further can flush the chain --
            # the window must be blind to the variable under test (#7h's rule).
            dut.pipe_data_valid_i.value = 0
            await ClockCycles(dut.pipe_rx_usr_clk_i, 60)
            h.kill()
            dut._log.info("SWEEP|gap=%d|tail=%d|beats=%d|data=%s"
                          % (gap, tail, len(beats),
                             ','.join('%08x/%x/%d' % b for b in beats)))


# ------------------------------------------------------------------ R7
# 1-b asks for the answer PER STAGE, not only at the closure.  R1-R6 observe
# the two ends -- ordered_set_handler (via idle_valid_o) and data_handler (via
# the AXIS port).  R7 adds the stage between them, which is the one with the
# history: block_alignment carried F16 (a missing `D = Q;` that latched
# data_valid_o high through idle) until §63 #7c.

@cocotb.test()
async def r7_per_stage_under_continuous_idle(dut):
    """Record each RX stage's own valid under 240 Symbols of continuous idle.

    descrambler      -> gen_lane_descramble[0].descrambler_inst.data_valid_o
    ordered_set_hdlr -> idle_valid_o            (already recorded, kept for phase)
    block_alignment  -> block_alignment_data_valid
    data_handler     -> m_dllp_axis_tvalid
    """
    await setup(dut)
    tx = Descrambler()

    def probe(path, default=-1):
        try:
            return int(path.value) & 0x1
        except Exception:
            return default

    stop = {"go": True}

    async def stage_mon():
        c = 0
        while stop["go"]:
            await RisingEdge(dut.pipe_rx_usr_clk_i)
            try:
                ba = int(dut.block_alignment_data_valid.value) & 1
            except Exception:
                ba = -1
            try:
                ds = int(dut.descrambler_data_valid.value) & 1
            except Exception:
                ds = -1
            dut._log.info("STAGE|%d|%.1f|%d|%d|%d|%d"
                          % (c, cocotb.utils.get_sim_time(units="ns"),
                             ds, _b0(dut.idle_valid_o), ba,
                             int(dut.m_dllp_axis_tvalid.value) & 1))
            c += 1

    cocotb.start_soon(stage_mon())
    await _drive(dut, [(tx.symbol(COM, is_k=True), 1)] + idle_run(tx, 240))
    stop["go"] = False
    await ClockCycles(dut.pipe_rx_usr_clk_i, 2)


# ------------------------------------------------------------------ R8
# WHERE does the tail stop?  The fragment at tail=4..6 is a symptom; before any
# fix is written the stranding stage has to be identified by measurement, not
# by reasoning about chain depths.  R8 drives the DLLP with a short tail and
# records every stage's DATA as well as its valid, so the last Symbol each
# stage passed can be read off directly.

@cocotb.test()
async def r8_where_does_the_tail_stop(dut):
    """Drive TS1 -> DLLP -> N trailing idle Symbols, for N in {4, 8}, and record
    per-stage data+valid for the whole window.  Raw lines only."""
    for tail in (4, 8):
        await setup(dut)
        tx = Descrambler()
        stop = {"go": True}

        async def mon(tag):
            c = 0
            while stop["go"]:
                await RisingEdge(dut.pipe_rx_usr_clk_i)
                def g(sig, w=0xFFFFFFFF):
                    try:
                        return int(sig.value) & w
                    except Exception:
                        return -1
                dut._log.info(
                    "TAIL|%s|%d|%.1f|in=%02x/%d/%d|ds=%08x/%x/%d|ba=%08x/%x/%d|pk=%08x/%x/%d|ax=%08x/%x/%d/%d"
                    % (tag, c, cocotb.utils.get_sim_time(units="ns"),
                       g(dut.pipe_data_i, 0xFF), g(dut.pipe_data_k_i, 1),
                       g(dut.pipe_data_valid_i, 1),
                       g(dut.descrambler_data), g(dut.descrambler_data_k, 0xF),
                       g(dut.descrambler_data_valid, 1),
                       g(dut.block_alignment_data), g(dut.block_alignment_data_k, 0xF),
                       g(dut.block_alignment_data_valid, 1),
                       g(dut.packer_data), g(dut.packer_data_k, 0xF),
                       g(dut.packer_data_valid, 1),
                       g(dut.m_dllp_axis_tdata), g(dut.m_dllp_axis_tkeep, 0xF),
                       g(dut.m_dllp_axis_tvalid, 1), g(dut.m_dllp_axis_tlast, 1)))
                c += 1

        cocotb.start_soon(mon("T%d" % tail))
        await _drive(dut, [(tx.symbol(COM, is_k=True), 1)] + ts1_prefix(tx))
        await _drive(dut, dllp_frame(tx, [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34]))
        await _drive(dut, idle_run(tx, tail))
        dut.pipe_data_valid_i.value = 0
        await ClockCycles(dut.pipe_rx_usr_clk_i, 40)
        stop["go"] = False
        await ClockCycles(dut.pipe_rx_usr_clk_i, 2)


# ------------------------------------------------------------------ R9
# Two packets with a variable idle gap between them.  Measured BEFORE the
# acceptance row is written, so the row can pin the real failure mode instead of
# an assumed one (§22.87: a red row's body encodes WHY it is red).

@cocotb.test()
async def r9_two_packets_gap_sweep_raw(dut):
    """TS1 -> DLLP(A) -> N idle -> DLLP(B) -> long tail, for N = 0..14.

    Raw one-line-per-case output; the classification is offline."""
    A = [0xDE, 0xAD, 0xBE, 0xEF, 0x12, 0x34]
    B = [0xC0, 0xFF, 0xEE, 0x99, 0x77, 0x55]
    for gap in range(0, 15, 2):
        await setup(dut)
        tx = Descrambler()
        beats = []

        async def mon():
            while True:
                await RisingEdge(dut.clk_i)
                if int(dut.m_dllp_axis_tvalid.value) & 1:
                    beats.append((int(dut.m_dllp_axis_tdata.value) & 0xFFFFFFFF,
                                  int(dut.m_dllp_axis_tkeep.value) & 0xF,
                                  int(dut.m_dllp_axis_tlast.value) & 1))

        h = cocotb.start_soon(mon())
        await _drive(dut, [(tx.symbol(COM, is_k=True), 1)] + ts1_prefix(tx))
        await _drive(dut, dllp_frame(tx, A))
        if gap:
            await _drive(dut, idle_run(tx, gap))
        await _drive(dut, dllp_frame(tx, B))
        await _drive(dut, idle_run(tx, 40))
        dut.pipe_data_valid_i.value = 0
        await ClockCycles(dut.pipe_rx_usr_clk_i, 60)
        h.kill()
        dut._log.info("GAP2|gap=%d|beats=%d|lasts=%d|data=%s"
                      % (gap, len(beats), sum(b[2] for b in beats),
                         ','.join('%08x/%x/%d' % b for b in beats)))
