// ===========================================================================
// pcie_rc_gth_top -- the Root Complex on the AMD PCIe PHY IP (PG239), one lane.
//
// sec 63 #5 (the GTH rung), sub-rung 8-2.  Three things and no logic:
//
//     pcie_rc_top    u_rc    enumeration engine + TL + DLL + LTSSM + logical PHY
//     pg239_gen1_x1  u_pg239 AMD PCIe PHY IP v1.0: 8b/10b, SERDES, CDR, RX
//                            elastic buffer, on GTH Quad 130 channel 0
//     IBUFDS_GTE4 + BUFG_GT  the reference-clock buffers PG239 requires
//
// Everything PCIe above the PIPE stays ours: the IP does 8b/10b and the
// serial side, and the LTSSM, the scrambler and everything above it are in
// u_rc (the claim line of D-8.3).  The IP instance is generated by
// ~/pcie_docs/evidence/gth-8/8-2/scripts/p0b_configure_generate_export.tcl
// (non-defaults: phy_max_speed 2.5_GT/s, lane0_gt_bank GTH_Quad_130) and is
// not in this repository; this file is in no .core, so the Verilator gate
// never elaborates it (xsim only, D-8.7).
//
// == THE PIPE WIRING (evidence/gth-8/8-2/PHASE0_8-2.md sec 4) ================
//
// 39 ports match the IP by name and direction.  Four differ in width:
// phy_txdata / phy_rxdata are [63:0] on the IP and 16 bits here (Gen1 uses
// [15:0]; PG239 Table 5 p.12 "Bits[31:16] ... must be ignored in Gen1 and
// Gen2"), phy_rxstart_block and phy_rate are 2 bits on the IP (1 and 3 here).
//
// Six of u_rc's PIPE outputs have no driver inside it (phy_txswing and the
// five Gen3/4 equalisation outputs).  They are left open and the IP's inputs
// are tied instead, each to the value PG239 makes safe: txswing 0b "Full
// swing (default)" (p.17), txeq_ctrl / rxeq_ctrl 00b "Idle" (pp.18-19),
// txeq_preset / txeq_coeff read only when txeq_ctrl is 01b / 10b (p.18),
// rxeq_txpreset "Gen3 and Gen4 only" (p.19).
//
// !! as_mac_in_detect / as_cdr_hold_req are wired straight through, and at
// 8-2 Phase 1 u_rc does not drive them (pcie_phy_top.sv declares them and
// assigns neither).  That is the unmodified RC the Phase 1 bench measures.
//
// == CLOCKS AND RESET ======================================================
//
// phy_pclk (125 MHz at Gen1, PG239 p.11) is the ONE design clock: it drives
// u_rc's clk_i and both PIPE user clocks, and leaves as pclk_o so logic on the
// RQ / RC / CQ / CC surface can be synchronous to it (D-7B.1).  CLK_PERIOD_NS
// is therefore fixed at 8.
//
// The refclk buffers are PG239's own form (its example top and p.22):
// IBUFDS_GTE4.O -> phy_gtrefclk; IBUFDS_GTE4.ODIV2 -> BUFG_GT -> phy_refclk,
// with the BUFG_GT's CE driven by gt_gtpowergood (p.21, "must be connected to
// the CE pin of the BUFG_GT that is driven by IBUFDS_GTE4").
//
// sys_rst_n is PCIe PERST#, active low, straight to phy_rst_n (p.11).  u_rc's
// rst_i is its inverse -- the one gate in this file.  u_rc's LTSSM and PHY
// datapath also hold in reset on phy_phystatus_rst (pcie_phy_top.sv), which is
// PG239's "PHY and GT resets complete" (p.16).
// ===========================================================================

module pcie_rc_gth_top
  import tlp_pkg::*;
  import pcie_rq_rc_pkg::*;
  import pcie_enum_pkg::*;
#(
    parameter int AXIS_DATA_WIDTH = 128,
    parameter int AXIS_KEEP_WIDTH = AXIS_DATA_WIDTH / 32,
    parameter int AXIS_USER_WIDTH = 60,
    parameter int CONTEXT_WIDTH   = 16,
    parameter int TAG_COUNT       = 32,
    parameter int unsigned CPL_TIMEOUT_CYCLES = tlp_pkg::CPL_TIMEOUT_DEFAULT_CYCLES,
    parameter int unsigned CRS_RETRY_MAX      = 3,
    parameter int unsigned CRS_BACKOFF_CYCLES = 8,
    parameter int CQ_USER_WIDTH   = 88,
    parameter int CC_USER_WIDTH   = 33,
    parameter int PHY_USER_WIDTH  = 5,
    parameter int IS_ROOT_PORT    = 1,
    parameter int LINK_NUM        = 0,
    parameter int SIM_FAST_LINK   = 0
) (
    // ---- the board side ----------------------------------------------------
    input  wire                         sys_clk_p,     // 100 MHz, MGTREFCLK0_130 (A5)
    input  wire                         sys_clk_n,
    input  wire                         sys_rst_n,     // PCIe PERST#, active low
    output wire [0:0]                   pci_exp_txp,
    output wire [0:0]                   pci_exp_txn,
    input  wire [0:0]                   pci_exp_rxp,
    input  wire [0:0]                   pci_exp_rxn,
    output wire                         pclk_o,        // = phy_pclk, the design clock

    input  logic                        en_i,
    input  logic                        transmit_enable_i,
    output wire [20:0]                  ltssm_debug_state,

    // =======================================================================
    // Link and flow-control state.  link_up_o is an OUTPUT here; the same
    // condition was an INPUT (phy_link_up_i) on every earlier RC top, because
    // the LTSSM that decides it now lives inside this module.
    // =======================================================================
    output logic                        link_up_o,
    output logic                        fc_initialized_o,   // UNFILTERED
    output logic                        fc_init_done_o,     // == fc_initialized_o
    output logic                        ok_to_issue_o,

    // ---- Root Complex identity (fixed BDF, 00:00.0) ------------------------
    input  logic [15:0]                 requester_id_i,
    input  logic [15:0]                 completer_id_i,
    input  logic [7:0]                  bus_number_i,
    input  logic [4:0]                  device_number_i,
    input  logic [2:0]                  function_number_i,
    input  logic                        memory_enable_i,
    input  logic                        extended_tag_enable_i,
    input  logic [12:0]                 max_payload_bytes_i,
    input  logic [12:0]                 max_read_bytes_i,
    input  logic                        rcb_128b_i,
    output logic [7:0]                  cfg_bus_number_o,
    output logic [4:0]                  cfg_device_number_o,
    output logic [2:0]                  cfg_function_number_o,

    // ---- Enumeration control ----------------------------------------------
    input  logic                        scan_start_i,
    input  logic [7:0]                  scan_bus_i,
    input  logic                        bar_enable_i,
    input  logic                        bridge_enable_i,

    // ---- Enumeration results, level 1 --------------------------------------
    output logic                        scan_busy_o,
    output logic                        scan_done_o,
    output logic                        scan_error_o,
    output enum_error_e                 scan_error_code_o,
    output logic                        err_credit_blocked_o,
    output logic                        device_present_o,
    output logic                        unsupported_device_o,
    output logic [15:0]                 device_bdf_o,
    output logic [15:0]                 vendor_id_o,
    output logic [15:0]                 device_id_o,
    output logic [7:0]                  header_type_o,
    output logic                        multifunction_o,
    output logic                        bar_busy_o,
    output logic                        enum_done_o,
    output logic                        enum_error_o,
    output enum_error_e                 enum_error_code_o,
    output logic [3:0]                  bar_count_o,
    output logic [BAR_SLOTS-1:0]        bar_valid_o,
    output logic [BAR_SLOTS-1:0]        bar_is_64_o,
    output logic [BAR_SLOTS-1:0]        bar_prefetch_o,
    output logic [BAR_SLOTS*64-1:0]     bar_size_o,
    output logic [BAR_SLOTS*64-1:0]     bar_addr_o,
    output logic [BAR_SLOTS-1:0]        io_bar_mask_o,

    // ---- Enumeration results, level 2 (bridge path) ------------------------
    output logic                        bus_done_o,
    output logic                        bus_bypassed_o,
    output logic                        sec_scan_done_o,
    output logic                        sec_device_present_o,
    output logic                        sec_unsupported_device_o,
    output logic [15:0]                 sec_device_bdf_o,
    output logic [15:0]                 sec_vendor_id_o,
    output logic [15:0]                 sec_device_id_o,
    output logic [7:0]                  sec_header_type_o,
    output logic                        sec_multifunction_o,
    output logic                        sec_enum_done_o,
    output logic [3:0]                  sec_bar_count_o,
    output logic [BAR_SLOTS-1:0]        sec_bar_valid_o,
    output logic [BAR_SLOTS-1:0]        sec_bar_is_64_o,
    output logic [BAR_SLOTS-1:0]        sec_bar_prefetch_o,
    output logic [BAR_SLOTS*64-1:0]     sec_bar_size_o,
    output logic [BAR_SLOTS*64-1:0]     sec_bar_addr_o,
    output logic [BAR_SLOTS-1:0]        sec_io_bar_mask_o,

    // =======================================================================
    // The requester surface -- row 4's entry point, and Stage G's.
    // The engine owns this socket until enum_done_o; after that these pins do.
    // =======================================================================
    input  logic [AXIS_DATA_WIDTH-1:0]  s_axis_rq_tdata,
    input  logic [AXIS_KEEP_WIDTH-1:0]  s_axis_rq_tkeep,
    input  logic                        s_axis_rq_tvalid,
    input  logic                        s_axis_rq_tlast,
    input  logic [AXIS_USER_WIDTH-1:0]  s_axis_rq_tuser,
    output logic                        s_axis_rq_tready,
    output logic [AXIS_DATA_WIDTH-1:0]  m_axis_rc_tdata,
    output logic [AXIS_KEEP_WIDTH-1:0]  m_axis_rc_tkeep,
    output logic                        m_axis_rc_tvalid,
    output logic                        m_axis_rc_tlast,
    input  logic                        m_axis_rc_tready,
    output logic [7:0]                  pcie_rq_tag_o,
    output logic                        pcie_rq_tag_vld_o,
    output logic                        rq_engine_owns_o,

    // ---- Completer surface -------------------------------------------------
    output logic [AXIS_DATA_WIDTH-1:0]  m_axis_cq_tdata,
    output logic [AXIS_KEEP_WIDTH-1:0]  m_axis_cq_tkeep,
    output logic                        m_axis_cq_tvalid,
    output logic                        m_axis_cq_tlast,
    output logic [CQ_USER_WIDTH-1:0]    m_axis_cq_tuser,
    input  logic                        m_axis_cq_tready,
    input  logic [AXIS_DATA_WIDTH-1:0]  s_axis_cc_tdata,
    input  logic [AXIS_KEEP_WIDTH-1:0]  s_axis_cc_tkeep,
    input  logic                        s_axis_cc_tvalid,
    input  logic                        s_axis_cc_tlast,
    input  logic [CC_USER_WIDTH-1:0]    s_axis_cc_tuser,
    output logic                        s_axis_cc_tready,
    output logic                        cq_dropped_o,
    output logic [3:0]                  cq_error_code_o,
    output logic                        cq_gearbox_error_o,
    output logic                        cc_protocol_error_o,
    output logic [3:0]                  cc_error_code_o,
    output logic                        cc_gearbox_error_o,

    // ---- Error surface -----------------------------------------------------
    output logic                        rq_protocol_error_o,
    output rq_error_e                   rq_error_code_o,
    output logic                        rq_gearbox_error_o,
    output logic                        rc_unexpected_completion_o,
    output tlp_error_e                  rc_completion_error_code_o,
    output logic                        rc_protocol_error_o,
    output rc_error_e                   rc_error_code_o,
    output logic                        rc_gearbox_error_o,
    output logic                        command_error_valid_o,
    output tlp_error_e                  command_error_code_o,
    output logic                        malformed_o,
    output logic                        rx_error_valid_o,
    output tlp_error_e                  rx_error_code_o,
    output logic                        rx_ecrc_error_o,
    output logic                        tx_error_valid_o,
    output tlp_error_e                  tx_error_code_o,
    output logic                        tx_fc_blocked_o,
    output logic                        credit_error_o,
    output logic                        vc_overflow_o,
    output logic                        cpl_timeout_valid_o,
    output logic [7:0]                  cpl_timeout_tag_o,
    output logic                        late_cpl_valid_o,
    output logic [7:0]                  late_cpl_tag_o,
    output logic [$clog2(TAG_COUNT+1)-1:0] outstanding_o
);

  // The IP instance is x1 Gen1 with a 16-bit PIPE; these are not choices here.
  localparam int MAX_NUM_LANES  = 1;
  localparam int PHY_DATA_WIDTH = 16;

  // ---- clocks and reset ---------------------------------------------------
  wire        sys_clk_gt;        // IBUFDS_GTE4.O     -> phy_gtrefclk
  wire        sys_clk_div2;      // IBUFDS_GTE4.ODIV2 -> BUFG_GT
  wire        sys_clk_bufg;      // BUFG_GT.O         -> phy_refclk
  wire [0:0]  gt_gtpowergood;
  wire        phy_pclk;

  IBUFDS_GTE4 refclk_ibuf (.O(sys_clk_gt), .ODIV2(sys_clk_div2), .I(sys_clk_p), .CEB(1'b0), .IB(sys_clk_n));
  BUFG_GT bufg_gt_sysclk (.CE(gt_gtpowergood[0]), .CEMASK(1'b0), .CLR(1'b0), .CLRMASK(1'b0),
                          .DIV(3'd0), .I(sys_clk_div2), .O(sys_clk_bufg));

  assign pclk_o = phy_pclk;

  // ---- the PIPE between u_rc and u_pg239 ----------------------------------
  wire [(MAX_NUM_LANES*PHY_DATA_WIDTH)-1:0]   phy_txdata;
  wire [MAX_NUM_LANES-1:0]                    phy_txdata_valid;
  wire [(MAX_NUM_LANES*PHY_DATA_WIDTH/8)-1:0] phy_txdatak;
  wire [MAX_NUM_LANES-1:0]                    phy_txstart_block;
  wire [(2*MAX_NUM_LANES)-1:0]                phy_txsync_header;
  wire [63:0]                                 pg_rxdata;          // IP width; [15:0] used
  wire [(MAX_NUM_LANES*PHY_DATA_WIDTH/8)-1:0] phy_rxdatak;
  wire [MAX_NUM_LANES-1:0]                    phy_rxdata_valid;
  wire [1:0]                                  pg_rxstart_block;   // IP width; [0] used
  wire [(2*MAX_NUM_LANES)-1:0]                phy_rxsync_header;

  wire                                        phy_txdetectrx;
  wire [MAX_NUM_LANES-1:0]                    phy_txelecidle;
  wire [MAX_NUM_LANES-1:0]                    phy_txcompliance;
  wire [MAX_NUM_LANES-1:0]                    phy_rxpolarity;
  wire [1:0]                                  phy_powerdown;
  wire [2:0]                                  phy_rate;           // ours is 3 bits; the IP takes [1:0]
  wire [MAX_NUM_LANES-1:0]                    phy_rxvalid;
  wire [MAX_NUM_LANES-1:0]                    phy_phystatus;
  wire                                        phy_phystatus_rst;
  wire [MAX_NUM_LANES-1:0]                    phy_rxelecidle;
  wire [(MAX_NUM_LANES*3)-1:0]                phy_rxstatus;
  wire [2:0]                                  phy_txmargin;
  wire                                        phy_txdeemph;

  wire [5:0]                                  phy_txeq_fs;
  wire [5:0]                                  phy_txeq_lf;
  wire [(MAX_NUM_LANES*18)-1:0]               phy_txeq_new_coeff;
  wire [MAX_NUM_LANES-1:0]                    phy_txeq_done;
  wire [MAX_NUM_LANES-1:0]                    phy_rxeq_preset_sel;
  wire [(MAX_NUM_LANES*18)-1:0]               phy_rxeq_new_txcoeff;
  wire [MAX_NUM_LANES-1:0]                    phy_rxeq_adapt_done;
  wire [MAX_NUM_LANES-1:0]                    phy_rxeq_done;

  wire                                        as_mac_in_detect;
  wire                                        as_cdr_hold_req;

  pcie_rc_top #(
      .AXIS_DATA_WIDTH   (AXIS_DATA_WIDTH),
      .AXIS_KEEP_WIDTH   (AXIS_KEEP_WIDTH),
      .AXIS_USER_WIDTH   (AXIS_USER_WIDTH),
      .CONTEXT_WIDTH     (CONTEXT_WIDTH),
      .TAG_COUNT         (TAG_COUNT),
      .CPL_TIMEOUT_CYCLES(CPL_TIMEOUT_CYCLES),
      .CRS_RETRY_MAX     (CRS_RETRY_MAX),
      .CRS_BACKOFF_CYCLES(CRS_BACKOFF_CYCLES),
      .CQ_USER_WIDTH     (CQ_USER_WIDTH),
      .CC_USER_WIDTH     (CC_USER_WIDTH),
      .CLK_PERIOD_NS     (8),              // phy_pclk, 125 MHz at Gen1
      .MAX_NUM_LANES     (MAX_NUM_LANES),
      .PHY_DATA_WIDTH    (PHY_DATA_WIDTH),
      .PHY_USER_WIDTH    (PHY_USER_WIDTH),
      .IS_ROOT_PORT      (IS_ROOT_PORT),
      .LINK_NUM          (LINK_NUM),
      .SIM_FAST_LINK     (SIM_FAST_LINK)
  ) u_rc (
      .clk_i            (phy_pclk),
      .rst_i            (~sys_rst_n),
      .en_i             (en_i),
      .pipe_rx_usr_clk_i(phy_pclk),
      .pipe_tx_usr_clk_i(phy_pclk),
      .transmit_enable_i(transmit_enable_i),

      .phy_txdata       (phy_txdata),
      .phy_txdata_valid (phy_txdata_valid),
      .phy_txdatak      (phy_txdatak),
      .phy_txstart_block(phy_txstart_block),
      .phy_txsync_header(phy_txsync_header),
      .phy_rxdata       (pg_rxdata[15:0]),
      .phy_rxdata_valid (phy_rxdata_valid),
      .phy_rxdatak      (phy_rxdatak),
      .phy_rxstart_block(pg_rxstart_block[0]),
      .phy_rxsync_header(phy_rxsync_header),

      .phy_txdetectrx  (phy_txdetectrx),
      .phy_txelecidle  (phy_txelecidle),
      .phy_txcompliance(phy_txcompliance),
      .phy_rxpolarity  (phy_rxpolarity),
      .phy_powerdown   (phy_powerdown),
      .phy_rate        (phy_rate),

      .phy_rxvalid      (phy_rxvalid),
      .phy_phystatus    (phy_phystatus),
      .phy_phystatus_rst(phy_phystatus_rst),
      .phy_rxelecidle   (phy_rxelecidle),
      .phy_rxstatus     (phy_rxstatus),

      .phy_txmargin(phy_txmargin),
      .phy_txswing (),                     // no driver in u_rc; the IP input is tied
      .phy_txdeemph(phy_txdeemph),
      .pipe_width_o(),

      .phy_txeq_ctrl       (),             // no driver in u_rc; tied at the IP
      .phy_txeq_preset     (),
      .phy_txeq_coeff      (),
      .phy_txeq_fs         (phy_txeq_fs),
      .phy_txeq_lf         (phy_txeq_lf),
      .phy_txeq_new_coeff  (phy_txeq_new_coeff),
      .phy_txeq_done       (phy_txeq_done),
      .phy_rxeq_ctrl       (),
      .phy_rxeq_txpreset   (),
      .phy_rxeq_preset_sel (phy_rxeq_preset_sel),
      .phy_rxeq_new_txcoeff(phy_rxeq_new_txcoeff),
      .phy_rxeq_adapt_done (phy_rxeq_adapt_done),
      .phy_rxeq_done       (phy_rxeq_done),

      .tx_elec_idle     (1'b0),            // read nowhere in pcie_phy_top
      .phy_ready_en     (1'b0),            // read nowhere in pcie_phy_top
      .as_mac_in_detect (as_mac_in_detect),
      .as_cdr_hold_req  (as_cdr_hold_req),
      .ltssm_debug_state(ltssm_debug_state),

      .link_up_o                   (link_up_o),
      .fc_initialized_o            (fc_initialized_o),
      .fc_init_done_o              (fc_init_done_o),
      .ok_to_issue_o               (ok_to_issue_o),
      .requester_id_i              (requester_id_i),
      .completer_id_i              (completer_id_i),
      .bus_number_i                (bus_number_i),
      .device_number_i             (device_number_i),
      .function_number_i           (function_number_i),
      .memory_enable_i             (memory_enable_i),
      .extended_tag_enable_i       (extended_tag_enable_i),
      .max_payload_bytes_i         (max_payload_bytes_i),
      .max_read_bytes_i            (max_read_bytes_i),
      .rcb_128b_i                  (rcb_128b_i),
      .cfg_bus_number_o            (cfg_bus_number_o),
      .cfg_device_number_o         (cfg_device_number_o),
      .cfg_function_number_o       (cfg_function_number_o),
      .scan_start_i                (scan_start_i),
      .scan_bus_i                  (scan_bus_i),
      .bar_enable_i                (bar_enable_i),
      .bridge_enable_i             (bridge_enable_i),
      .scan_busy_o                 (scan_busy_o),
      .scan_done_o                 (scan_done_o),
      .scan_error_o                (scan_error_o),
      .scan_error_code_o           (scan_error_code_o),
      .err_credit_blocked_o        (err_credit_blocked_o),
      .device_present_o            (device_present_o),
      .unsupported_device_o        (unsupported_device_o),
      .device_bdf_o                (device_bdf_o),
      .vendor_id_o                 (vendor_id_o),
      .device_id_o                 (device_id_o),
      .header_type_o               (header_type_o),
      .multifunction_o             (multifunction_o),
      .bar_busy_o                  (bar_busy_o),
      .enum_done_o                 (enum_done_o),
      .enum_error_o                (enum_error_o),
      .enum_error_code_o           (enum_error_code_o),
      .bar_count_o                 (bar_count_o),
      .bar_valid_o                 (bar_valid_o),
      .bar_is_64_o                 (bar_is_64_o),
      .bar_prefetch_o              (bar_prefetch_o),
      .bar_size_o                  (bar_size_o),
      .bar_addr_o                  (bar_addr_o),
      .io_bar_mask_o               (io_bar_mask_o),
      .bus_done_o                  (bus_done_o),
      .bus_bypassed_o              (bus_bypassed_o),
      .sec_scan_done_o             (sec_scan_done_o),
      .sec_device_present_o        (sec_device_present_o),
      .sec_unsupported_device_o    (sec_unsupported_device_o),
      .sec_device_bdf_o            (sec_device_bdf_o),
      .sec_vendor_id_o             (sec_vendor_id_o),
      .sec_device_id_o             (sec_device_id_o),
      .sec_header_type_o           (sec_header_type_o),
      .sec_multifunction_o         (sec_multifunction_o),
      .sec_enum_done_o             (sec_enum_done_o),
      .sec_bar_count_o             (sec_bar_count_o),
      .sec_bar_valid_o             (sec_bar_valid_o),
      .sec_bar_is_64_o             (sec_bar_is_64_o),
      .sec_bar_prefetch_o          (sec_bar_prefetch_o),
      .sec_bar_size_o              (sec_bar_size_o),
      .sec_bar_addr_o              (sec_bar_addr_o),
      .sec_io_bar_mask_o           (sec_io_bar_mask_o),
      .s_axis_rq_tdata             (s_axis_rq_tdata),
      .s_axis_rq_tkeep             (s_axis_rq_tkeep),
      .s_axis_rq_tvalid            (s_axis_rq_tvalid),
      .s_axis_rq_tlast             (s_axis_rq_tlast),
      .s_axis_rq_tuser             (s_axis_rq_tuser),
      .s_axis_rq_tready            (s_axis_rq_tready),
      .m_axis_rc_tdata             (m_axis_rc_tdata),
      .m_axis_rc_tkeep             (m_axis_rc_tkeep),
      .m_axis_rc_tvalid            (m_axis_rc_tvalid),
      .m_axis_rc_tlast             (m_axis_rc_tlast),
      .m_axis_rc_tready            (m_axis_rc_tready),
      .pcie_rq_tag_o               (pcie_rq_tag_o),
      .pcie_rq_tag_vld_o           (pcie_rq_tag_vld_o),
      .rq_engine_owns_o            (rq_engine_owns_o),
      .m_axis_cq_tdata             (m_axis_cq_tdata),
      .m_axis_cq_tkeep             (m_axis_cq_tkeep),
      .m_axis_cq_tvalid            (m_axis_cq_tvalid),
      .m_axis_cq_tlast             (m_axis_cq_tlast),
      .m_axis_cq_tuser             (m_axis_cq_tuser),
      .m_axis_cq_tready            (m_axis_cq_tready),
      .s_axis_cc_tdata             (s_axis_cc_tdata),
      .s_axis_cc_tkeep             (s_axis_cc_tkeep),
      .s_axis_cc_tvalid            (s_axis_cc_tvalid),
      .s_axis_cc_tlast             (s_axis_cc_tlast),
      .s_axis_cc_tuser             (s_axis_cc_tuser),
      .s_axis_cc_tready            (s_axis_cc_tready),
      .cq_dropped_o                (cq_dropped_o),
      .cq_error_code_o             (cq_error_code_o),
      .cq_gearbox_error_o          (cq_gearbox_error_o),
      .cc_protocol_error_o         (cc_protocol_error_o),
      .cc_error_code_o             (cc_error_code_o),
      .cc_gearbox_error_o          (cc_gearbox_error_o),
      .rq_protocol_error_o         (rq_protocol_error_o),
      .rq_error_code_o             (rq_error_code_o),
      .rq_gearbox_error_o          (rq_gearbox_error_o),
      .rc_unexpected_completion_o  (rc_unexpected_completion_o),
      .rc_completion_error_code_o  (rc_completion_error_code_o),
      .rc_protocol_error_o         (rc_protocol_error_o),
      .rc_error_code_o             (rc_error_code_o),
      .rc_gearbox_error_o          (rc_gearbox_error_o),
      .command_error_valid_o       (command_error_valid_o),
      .command_error_code_o        (command_error_code_o),
      .malformed_o                 (malformed_o),
      .rx_error_valid_o            (rx_error_valid_o),
      .rx_error_code_o             (rx_error_code_o),
      .rx_ecrc_error_o             (rx_ecrc_error_o),
      .tx_error_valid_o            (tx_error_valid_o),
      .tx_error_code_o             (tx_error_code_o),
      .tx_fc_blocked_o             (tx_fc_blocked_o),
      .credit_error_o              (credit_error_o),
      .vc_overflow_o               (vc_overflow_o),
      .cpl_timeout_valid_o         (cpl_timeout_valid_o),
      .cpl_timeout_tag_o           (cpl_timeout_tag_o),
      .late_cpl_valid_o            (late_cpl_valid_o),
      .late_cpl_tag_o              (late_cpl_tag_o),
      .outstanding_o               (outstanding_o)
  );

  pg239_gen1_x1 u_pg239 (
      .phy_refclk        (sys_clk_bufg),
      .phy_gtrefclk      (sys_clk_gt),
      .phy_rst_n         (sys_rst_n),
      .phy_pclk          (phy_pclk),
      .phy_coreclk       (),
      .phy_userclk       (),
      .phy_mcapclk       (),

      .phy_txdata        ({48'd0, phy_txdata}),   // [63:16] "must be ignored in Gen1" (p.12)
      .phy_txdatak       (phy_txdatak),
      .phy_txdata_valid  (phy_txdata_valid),
      .phy_txstart_block (phy_txstart_block),
      .phy_txsync_header (phy_txsync_header),
      .phy_rxp           (pci_exp_rxp),
      .phy_rxn           (pci_exp_rxn),
      .phy_txp           (pci_exp_txp),
      .phy_txn           (pci_exp_txn),
      .phy_rxdata        (pg_rxdata),
      .phy_rxdatak       (phy_rxdatak),
      .phy_rxdata_valid  (phy_rxdata_valid),
      .phy_rxstart_block (pg_rxstart_block),
      .phy_rxsync_header (phy_rxsync_header),

      .phy_txdetectrx    (phy_txdetectrx),
      .phy_txelecidle    (phy_txelecidle),
      .phy_txcompliance  (phy_txcompliance),
      .phy_rxpolarity    (phy_rxpolarity),
      .phy_powerdown     (phy_powerdown),
      .phy_rate          (phy_rate[1:0]),         // 2 bits on UltraScale+ (p.16)
      .phy_rxvalid       (phy_rxvalid),
      .phy_phystatus     (phy_phystatus),
      .phy_phystatus_rst (phy_phystatus_rst),
      .phy_rxelecidle    (phy_rxelecidle),
      .phy_rxstatus      (phy_rxstatus),

      .phy_txmargin      (phy_txmargin),
      .phy_txswing       (1'b0),                  // p.17 "0b: Full swing (default)"
      .phy_txdeemph      (phy_txdeemph),

      .phy_txeq_ctrl     (2'b00),                 // p.18 "00b: Idle"
      .phy_txeq_preset   (4'd0),                  // p.18 read only when txeq_ctrl = 01b
      .phy_txeq_coeff    (6'd0),                  // p.18 read only when txeq_ctrl = 10b
      .phy_txeq_fs       (phy_txeq_fs),
      .phy_txeq_lf       (phy_txeq_lf),
      .phy_txeq_new_coeff(phy_txeq_new_coeff),
      .phy_txeq_done     (phy_txeq_done),
      .phy_rxeq_ctrl     (2'b00),                 // p.19 "00b: Idle"
      .phy_rxeq_txpreset (4'd0),                  // p.19 "Gen3 and Gen4 only"
      .phy_rxeq_preset_sel (phy_rxeq_preset_sel),
      .phy_rxeq_new_txcoeff(phy_rxeq_new_txcoeff),
      .phy_rxeq_adapt_done (phy_rxeq_adapt_done),
      .phy_rxeq_done       (phy_rxeq_done),

      .as_mac_in_detect  (as_mac_in_detect),
      .as_cdr_hold_req   (as_cdr_hold_req),
      .gt_gtpowergood    (gt_gtpowergood)
  );

endmodule
